// <auto-generated />
using System;
using Books.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Books.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Books.Entites.Concrete.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(3721),
                            FirstName = "Michelle",
                            LastName = "Alexander",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(3734),
                            FirstName = "Stephen E.",
                            LastName = "Ambrose",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(3734),
                            FirstName = "Margaret",
                            LastName = "Atwood",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(3734),
                            FirstName = "Jane",
                            LastName = "Austen",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(3737),
                            FirstName = "James",
                            LastName = "Baldwin",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(3737),
                            FirstName = "Emily",
                            LastName = "Bronte",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(3737),
                            FirstName = "Agatha",
                            LastName = "Christie",
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(3741),
                            FirstName = "Ta-Nehisi",
                            LastName = "Coates",
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(3741),
                            FirstName = "Jared",
                            LastName = "Diamond",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(3741),
                            FirstName = "Joan",
                            LastName = "Didion",
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(3744),
                            FirstName = "Daphne",
                            LastName = "Du Maurier",
                            Status = 1
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(3744),
                            FirstName = "Tina",
                            LastName = "Fey",
                            Status = 1
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(3744),
                            FirstName = "Roxane",
                            LastName = "Gay",
                            Status = 1
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(3747),
                            FirstName = "Dashiel",
                            LastName = "Hammett",
                            Status = 1
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(3747),
                            FirstName = "Frank",
                            LastName = "Herbert",
                            Status = 1
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(3747),
                            FirstName = "Aldous",
                            LastName = "Huxley",
                            Status = 1
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(3751),
                            FirstName = "Stieg",
                            LastName = "Larsson",
                            Status = 1
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(3751),
                            FirstName = "David",
                            LastName = "McCullough",
                            Status = 1
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(3754),
                            FirstName = "Toni",
                            LastName = "Morrison",
                            Status = 1
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(3754),
                            FirstName = "George",
                            LastName = "Orwell",
                            Status = 1
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(3754),
                            FirstName = "Mary",
                            LastName = "Shelley",
                            Status = 1
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(3757),
                            FirstName = "Sun",
                            LastName = "Tzu",
                            Status = 1
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(3757),
                            FirstName = "Augusten",
                            LastName = "Burroughs",
                            Status = 1
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(3757),
                            FirstName = "JK",
                            LastName = "Rowling",
                            Status = 1
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(3760),
                            FirstName = "Seth",
                            LastName = "Grahame-Smith",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Books.Entites.Concrete.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenreId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4088),
                            GenreId = "history",
                            Price = 18.0,
                            Status = 1,
                            Title = "1776"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4092),
                            GenreId = "scifi",
                            Price = 5.5,
                            Status = 1,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4095),
                            GenreId = "mystery",
                            Price = 4.5,
                            Status = 1,
                            Title = "And Then There Were None"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4095),
                            GenreId = "history",
                            Price = 11.5,
                            Status = 1,
                            Title = "Band of Brothers"
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4098),
                            GenreId = "novel",
                            Price = 10.99,
                            Status = 1,
                            Title = "Beloved"
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4098),
                            GenreId = "memoir",
                            Price = 13.5,
                            Status = 1,
                            Title = "Between the World and Me"
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4098),
                            GenreId = "memoir",
                            Price = 4.25,
                            Status = 1,
                            Title = "Bossypants"
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4098),
                            GenreId = "scifi",
                            Price = 16.25,
                            Status = 1,
                            Title = "Brave New World"
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4101),
                            GenreId = "history",
                            Price = 15.0,
                            Status = 1,
                            Title = "D-Day"
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4101),
                            GenreId = "memoir",
                            Price = 12.5,
                            Status = 1,
                            Title = "Down and Out in Paris and London"
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4105),
                            GenreId = "scifi",
                            Price = 8.75,
                            Status = 1,
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4105),
                            GenreId = "novel",
                            Price = 9.0,
                            Status = 1,
                            Title = "Emma"
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4105),
                            GenreId = "scifi",
                            Price = 6.5,
                            Status = 1,
                            Title = "Frankenstein"
                        },
                        new
                        {
                            Id = 14,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4108),
                            GenreId = "novel",
                            Price = 10.25,
                            Status = 1,
                            Title = "Go Tell it on the Mountain"
                        },
                        new
                        {
                            Id = 15,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4108),
                            GenreId = "history",
                            Price = 15.5,
                            Status = 1,
                            Title = "Guns, Germs, and Steel"
                        },
                        new
                        {
                            Id = 16,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4108),
                            GenreId = "memoir",
                            Price = 14.5,
                            Status = 1,
                            Title = "Hunger"
                        },
                        new
                        {
                            Id = 17,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4111),
                            GenreId = "mystery",
                            Price = 6.75,
                            Status = 1,
                            Title = "Murder on the Orient Express"
                        },
                        new
                        {
                            Id = 18,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4111),
                            GenreId = "novel",
                            Price = 8.5,
                            Status = 1,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 19,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4111),
                            GenreId = "mystery",
                            Price = 10.99,
                            Status = 1,
                            Title = "Rebecca"
                        },
                        new
                        {
                            Id = 20,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4115),
                            GenreId = "history",
                            Price = 5.75,
                            Status = 1,
                            Title = "The Art of War"
                        },
                        new
                        {
                            Id = 21,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4115),
                            GenreId = "mystery",
                            Price = 8.5,
                            Status = 1,
                            Title = "The Girl with the Dragon Tattoo"
                        },
                        new
                        {
                            Id = 22,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4115),
                            GenreId = "scifi",
                            Price = 12.5,
                            Status = 1,
                            Title = "The Handmaid's Tale"
                        },
                        new
                        {
                            Id = 23,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4118),
                            GenreId = "mystery",
                            Price = 10.99,
                            Status = 1,
                            Title = "The Maltese Falcon"
                        },
                        new
                        {
                            Id = 24,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4118),
                            GenreId = "history",
                            Price = 13.75,
                            Status = 1,
                            Title = "The New Jim Crow"
                        },
                        new
                        {
                            Id = 25,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4118),
                            GenreId = "memoir",
                            Price = 13.5,
                            Status = 1,
                            Title = "The Year of Magical Thinking"
                        },
                        new
                        {
                            Id = 26,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4121),
                            GenreId = "novel",
                            Price = 9.0,
                            Status = 1,
                            Title = "Wuthering Heights"
                        },
                        new
                        {
                            Id = 27,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4121),
                            GenreId = "memoir",
                            Price = 11.0,
                            Status = 1,
                            Title = "Running With Scissors"
                        },
                        new
                        {
                            Id = 28,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4121),
                            GenreId = "novel",
                            Price = 8.75,
                            Status = 1,
                            Title = "Pride and Prejudice and Zombies"
                        },
                        new
                        {
                            Id = 29,
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4125),
                            GenreId = "novel",
                            Price = 9.75,
                            Status = 1,
                            Title = "Harry Potter and the Sorcerer's Stone"
                        });
                });

            modelBuilder.Entity("Books.Entites.Concrete.BooksAuthors", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookAuthors");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 18
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 20
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 7
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 2
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 19
                        },
                        new
                        {
                            BookId = 6,
                            AuthorId = 8
                        },
                        new
                        {
                            BookId = 7,
                            AuthorId = 12
                        },
                        new
                        {
                            BookId = 8,
                            AuthorId = 16
                        },
                        new
                        {
                            BookId = 9,
                            AuthorId = 2
                        },
                        new
                        {
                            BookId = 10,
                            AuthorId = 20
                        },
                        new
                        {
                            BookId = 11,
                            AuthorId = 15
                        },
                        new
                        {
                            BookId = 12,
                            AuthorId = 4
                        },
                        new
                        {
                            BookId = 13,
                            AuthorId = 21
                        },
                        new
                        {
                            BookId = 14,
                            AuthorId = 5
                        },
                        new
                        {
                            BookId = 15,
                            AuthorId = 9
                        },
                        new
                        {
                            BookId = 16,
                            AuthorId = 13
                        },
                        new
                        {
                            BookId = 17,
                            AuthorId = 7
                        },
                        new
                        {
                            BookId = 18,
                            AuthorId = 4
                        },
                        new
                        {
                            BookId = 19,
                            AuthorId = 11
                        },
                        new
                        {
                            BookId = 20,
                            AuthorId = 22
                        },
                        new
                        {
                            BookId = 21,
                            AuthorId = 17
                        },
                        new
                        {
                            BookId = 22,
                            AuthorId = 3
                        },
                        new
                        {
                            BookId = 23,
                            AuthorId = 14
                        },
                        new
                        {
                            BookId = 24,
                            AuthorId = 1
                        },
                        new
                        {
                            BookId = 25,
                            AuthorId = 10
                        },
                        new
                        {
                            BookId = 26,
                            AuthorId = 6
                        },
                        new
                        {
                            BookId = 27,
                            AuthorId = 23
                        },
                        new
                        {
                            BookId = 28,
                            AuthorId = 4
                        },
                        new
                        {
                            BookId = 28,
                            AuthorId = 26
                        },
                        new
                        {
                            BookId = 29,
                            AuthorId = 25
                        });
                });

            modelBuilder.Entity("Books.Entites.Concrete.Genre", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = "novel",
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4207),
                            Name = "Novel",
                            Status = 1
                        },
                        new
                        {
                            Id = "memoir",
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4211),
                            Name = "Memoir",
                            Status = 1
                        },
                        new
                        {
                            Id = "mystery",
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4211),
                            Name = "Mystery",
                            Status = 1
                        },
                        new
                        {
                            Id = "scifi",
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4214),
                            Name = "Science Finction",
                            Status = 1
                        },
                        new
                        {
                            Id = "history",
                            CreateDate = new DateTime(2022, 6, 2, 11, 47, 22, 662, DateTimeKind.Local).AddTicks(4214),
                            Name = "History",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Books.Entites.Concrete.Book", b =>
                {
                    b.HasOne("Books.Entites.Concrete.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Books.Entites.Concrete.BooksAuthors", b =>
                {
                    b.HasOne("Books.Entites.Concrete.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Books.Entites.Concrete.Book", "Book")
                        .WithMany("BooksAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Books.Entites.Concrete.Author", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("Books.Entites.Concrete.Book", b =>
                {
                    b.Navigation("BooksAuthors");
                });

            modelBuilder.Entity("Books.Entites.Concrete.Genre", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
